import { NextResponse } from "next/server";
import { Groq } from "groq-sdk";

export async function POST(req: Request) {
  try {
    const { topic, category, count = 5 } = await req.json();

    const topicName = topic || "General Science & Mathematics";
    const categoryName = category || "General Education";
    const numQuestions = Math.min(Math.max(Number(count) || 5, 1), 10);

    let questions: Array<{
      id: number;
      question: string;
      options: string[];
      correctAnswer: number;
      explanation: string;
    }> = [];

    // 1. Call Groq API with valid available models
    if (process.env.GROQ_API_KEY) {
      try {
        const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

        const promptText = `Generate strictly a JSON array of ${numQuestions} multiple choice questions (MCQ) for students on the topic "${topicName}" under category "${categoryName}".
Each item must have:
- "id": number (1 to ${numQuestions})
- "question": clear question string
- "options": array of 4 options (strings)
- "correctAnswer": number index of correct option (0, 1, 2, or 3)
- "explanation": concise explanation of why the correct option is right.

Return ONLY raw valid JSON array, no markdown formatting or text wrappers.`;

        const modelsToTry = [
          "openai/gpt-oss-120b",
          "openai/gpt-oss-20b",
          "qwen/qwen3.6-27b",
          "groq/compound",
          "groq/compound-mini",
        ];

        for (const modelName of modelsToTry) {
          try {
            const chatCompletion = await groq.chat.completions.create({
              messages: [
                {
                  role: "user",
                  content: promptText,
                },
              ],
              model: modelName,
              temperature: 0.7,
              max_tokens: 2048,
            });

            const text = chatCompletion.choices[0]?.message?.content;
            if (text) {
              const cleanJson = text.replace(/```json/g, "").replace(/```/g, "").trim();
              const parsed = JSON.parse(cleanJson);
              if (Array.isArray(parsed) && parsed.length > 0) {
                questions = parsed;
                console.log(`Groq AI MCQ Success using model [${modelName}]`);
                break;
              }
            }
          } catch (modelErr: any) {
            console.warn(`Groq model ${modelName} MCQ generation failed:`, modelErr?.message || modelErr);
          }
        }
      } catch (groqErr) {
        console.warn("Groq SDK MCQ error:", groqErr);
      }
    }

    // 2. Try Gemini API if no questions generated by Groq yet
    if ((!questions || questions.length === 0) && process.env.GEMINI_API_KEY) {
      try {
        const geminiRes = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [
                {
                  parts: [
                    {
                      text: `Generate strictly a JSON array of ${numQuestions} multiple choice questions (MCQ) for students on the topic "${topicName}" under category "${categoryName}".
Each item must have:
- "id": number (1 to ${numQuestions})
- "question": clear question string
- "options": array of 4 options (strings)
- "correctAnswer": number index of correct option (0, 1, 2, or 3)
- "explanation": concise explanation of why the correct option is right.

Return ONLY raw valid JSON array, no markdown formatting or text wrappers.`,
                    },
                  ],
                },
              ],
            }),
          }
        );

        if (geminiRes.ok) {
          const rawData = await geminiRes.json();
          const text = rawData?.candidates?.[0]?.content?.parts?.[0]?.text;
          if (text) {
            const cleanJson = text.replace(/```json/g, "").replace(/```/g, "").trim();
            questions = JSON.parse(cleanJson);
          }
        }
      } catch (geminiErr) {
        console.warn("Gemini API call error:", geminiErr);
      }
    }

    if (questions && questions.length > 0) {
      return NextResponse.json({
        success: true,
        topic: topicName,
        category: categoryName,
        count: questions.length,
        questions,
      });
    }

    return NextResponse.json(
      { success: false, error: "Failed to generate AI questions. Please try again." },
      { status: 500 }
    );
  } catch (error: any) {
    console.error("MCQ Generation Error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to generate questions" },
      { status: 500 }
    );
  }
}
